import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Nav from '../components/Navbar';
import Arrivals from '../components/Arrivals';
import Offer from '../components/Offer';
import ProductCard from '../components/ProductCard';
import ProductContainer from '../components/ProductContainer';
import { Text } from '@nextui-org/react';

export default function Home() {
  const data = [
    {
      image:
        'https://cdn.shopify.com/s/files/1/0040/7201/3924/products/IMG_6706.jpg?v=1662115247',
      brand: 'TRIPOWIN',
      name: 'Cencibel',
      subTitle: 'High-resolution dynamic driver IEM',
      price: '44.10',
      description: [
        'Singularity in Sound',
        'Balanced Tonal Signature',
        '3D Designed and Constructed',
        'Detachable Cable',
      ],
      rating: [20, 3],
    },
    {
      image:
        'https://cdn.shopify.com/s/files/1/0040/7201/3924/products/TANCHJIMNewHANA-1-1000PX.jpg?v=1625795693',
      brand: 'TANCHJIM',
      name: 'New Hana',
      subTitle: 'DMT Dynamic HiFi In-Ear Monitoring',
      price: '152.99',
      description: [
        'Porcelain Imitation Enamel Process ',
        'High conductive OFC Cable ',
        '0.78/2pin Stable Connection ',
        'Compact And Lightweight ',
      ],
      rating: [20, 3],
    },
    {
      image:
        'https://cdn.shopify.com/s/files/1/0040/7201/3924/products/a3f98c6cd74d6a0a20a78a23cafe1827_2048x2048_70437138-2b7d-4f60-94e2-37792a4204ad.jpg?v=1662455620',
      brand: 'NFAUDIO',
      name: 'NA3',
      subTitle: 'Essentials Dynamic Driver Double Cavity In-Ear Monitor',
      price: '62.99',
      rating: [20, 3],
      description: [
        'Integrated Tuning Circuit',
        'High-performance NIB magnet',
        ' Dual Cavity Design',
        '5u High Polymer Composite Diaphragm ',
        'High-Quality Cable & Multiple Set Of Ear Tips',
        'High-Quality Cable & Multiple Set Of Ear Tips ',
      ],
    },
    {
      image:
        'https://cdn.shopify.com/s/files/1/0040/7201/3924/products/XennsUp6.jpg?v=1624517124',
      brand: 'Mangird',
      name: 'XENNS UP',
      subTitle:
        '2 Electrostatic Driver + 4BA + 1DD Hybrid Driver In-ear Earphone',
      price: '109',
      rating: [20, 3],
      description: [
        'Hand-painted Faceplate+Resin Shell',
        '6N OCC Silver-plated Detachable Cable',
        '2EST+4BA+1DD Driver ',
      ],
    },
    {
      image:
        'https://cdn.shopify.com/s/files/1/0040/7201/3924/products/KZ-ZSNPRO-IEM-1.jpg?v=1567348966',
      brand: 'KZ',
      name: 'ZSN PRO',
      subTitle: '1BA+1DD HiFi Hybrid Dual Driver In Ear Earbuds',
      price: '17.85',
      rating: [20, 3],
      description: [
        'Improved Hybrid Drivers',
        'Exquisite Metal and Resin Design',
        'Improved 0.75mm 2 Pin Detachable Cable',
        'Ergonomic Design for Stable Wear',
      ],
    },
    {
      image:
        'https://cdn.shopify.com/s/files/1/0040/7201/3924/products/5_99b91698-08fb-4661-815c-47a8e745c894.jpg?v=1629800987',
      brand: 'KZ',
      name: 'ZS10 PRO',
      subTitle:
        '4BA+1DD 5 Driver in-Ear HiFi Metal Earphones with Stainless Steel Faceplate, 2 Pin Detachable Cable',
      price: '45.00',
      description: [
        'Upgraded 4BA+1DD Hybrid Earphones&Magnetic Dynamic Unit',
        'Exquisite Craft',
        'PCB Frequency Dividing Board',
        'Ergonomic Design & Noise Canceling',
      ],
      rating: [20, 3],
    },
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title>Hifility</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Nav />
      <main>
        <section className={styles.curved}>
          <div className={styles.flex}>
            <Arrivals />
            <Offer />
          </div>
          <Text
            h1
            size={40}
            css={{
              textAlign: 'center',
              textGradient: '45deg, grey, black',
            }}
            weight='bold'
          >
            Featured
          </Text>
          <div className={styles.flexRow}>
            {data.map((item) => {
              return (
                <ProductCard
                  key={item.name}
                  name={item.name}
                  brand={item.brand}
                  image={item.image}
                  price={item.price}
                />
              );
            })}
          </div>
        </section>
        <section className={styles.curved2}>
          <div className={styles.flex}>
            <ProductContainer />
          </div>
        </section>
        <section>
          <div></div>
        </section>
      </main>
    </div>
  );
}
