import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Nav from '../components/Navbar';
import Arrivals from '../components/Arrivals';
import Offer from '../components/Offer';
import ProductCard from '../components/ProductCard';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Nav />
      <main>
        <div className={styles.flex}>
          <Arrivals />
          <Offer />
        </div>
        <div>
          <ProductCard />
        </div>
      </main>
    </div>
  );
}
