import { useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Nav from '../components/Navbar';
import Arrivals from '../components/Arrivals';
import Offer from '../components/Offer';
import ProductCard from '../components/ProductCard';
import ProductContainer from '../components/ProductContainer';
import { changeTheme, Text } from '@nextui-org/react';

export default function Home({ productData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hifility</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Nav />
      <main>
        <section className={styles.curved}>
          <div className={styles.flex}>
            <Arrivals />
            <Offer />
          </div>
          <Text
            h1
            size={40}
            css={{
              textAlign: 'center',
              textGradient: '45deg, grey, black',
            }}
            weight='bold'
          >
            Featured
          </Text>
          <div className={styles.flexRow}>
            {productData.data.slice(0, 5).map((item) => {
              return (
                <ProductCard
                  key={item.name}
                  name={item.name}
                  brand={item.brand}
                  image={item.image}
                  price={item.price}
                />
              );
            })}
          </div>
        </section>
        <section className={styles.curved2}>
          <div className={styles.flex}>
            <ProductContainer productData={productData.data} />
          </div>
        </section>
        <section>
          <div></div>
        </section>
      </main>
    </div>
  );
}
export async function getServerSideProps({ params }) {
  const productApi = await fetch(`http://localhost:8080/product/show`, {
    method: 'GET',
  });
  const productData = await productApi.json();

  return {
    props: {
      productData,
    }, // will be passed to the page component as props
  };
}
